apiVersion: v1
kind: Service
metadata:
  name: jobber-auth
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: jobber-auth
  ports:
  - name: auth
    port: 8081
    targetPort: 8081
    protocol: TCP


    