apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber-auth
  namespace: production
  labels:
    app: jobber-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobber-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: jobber-auth
    spec:
      containers:
        - name: jobber-auth
          image: mukeshkr24/jobberapp-auth-service
          imagePullPolicy: Always
          ports:
            - name: auth
              containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-registry:8761/eureka"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/jobber_dev"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION
              value: "true"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
              value: "10"
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "150Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
