version: "3.8"

services:
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - jobber-network

  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - jobber-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - config-server
    networks:
      - jobber-network

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
      - config-server
    networks:
      - jobber-network

  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - config-server
    networks:
      - jobber-network

networks:
  jobber-network:
    driver: bridge
