apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: production
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: mukeshkr24/jobberapp-service-registry
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          resources:
            limits:
              cpu: "300m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always
