version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: jobber-postgres-dev
    environment:
      POSTGRES_DB: jobber_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - jobber-network-dev
  mongo:
    image: mongo:6.0
    container_name: jobber-mongo-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: jobber_mongo
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - jobber-network-dev

  # eureka:
  #   build:
  #     context: ./service-registry
  #     dockerfile: Dockerfile
  #   container_name: jobber-eureka-dev
  #   ports:
  #     - "8761:8761"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   networks:
  #     - jobber-network-dev
  #   depends_on:
  #     - postgres

  # config-server:
  #   build:
  #     context: ./config-server
  #     dockerfile: Dockerfile
  #   container_name: jobber-config-server-dev
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   networks:
  #     - jobber-network-dev
  #   depends_on:
  #     - postgres

  # auth-service:
  #   build:
  #     context: ./auth-service
  #     dockerfile: Dockerfile
  #   container_name: jobber-auth-service-dev
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #     JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
  #   networks:
  #     - jobber-network-dev
  #   depends_on:
  #     - config-server
  #     - eureka

  # user-service:
  #   build:
  #     context: ./user-service
  #     dockerfile: Dockerfile
  #   container_name: jobber-user-service-dev
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #     JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:5006,server=y,suspend=n"
  #   networks:
  #     - jobber-network-dev
  #   depends_on:
  #     - config-server
  #     - eureka

  # api-gateway:
  #   build:
  #     context: ./api-gateway
  #     dockerfile: Dockerfile
  #   container_name: jobber-api-gateway-dev
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #     JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:5007,server=y,suspend=n"
  #   networks:
  #     - jobber-network-dev
  #   depends_on:
  #     - config-server
  #     - eureka

networks:
  jobber-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
  mongo_data_dev:
