version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: jobber-postgres-dev
    environment:
      POSTGRES_DB: jobber_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - jobber-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6.0
    container_name: jobber-mongo-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: jobber_mongo
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - jobber-network-dev
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  jobber-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
  mongo_data_dev: